### ISSUE TITLE
[BUG] Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#10]
## 🐛 Bug Issue

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

## 🔍 To-do

- [x] webpack에 svg 로더 설정하기

**Comment by ramrami-B** [comment]
## 📚 References
[공식 문서](https://webpack.js.org/concepts/#loaders)
[[React] Webpack에서 SVG 설정하기]()
[npm file-loader](https://www.npmjs.com/package/file-loader)

**Comment by ramrami-B** [comment]
d0229b6db9a03b18657e45d2a3ea663fb2919d0a

**Comment by ramrami-B** [comment]
@alex-koko 확인 후 이슈 닫아 주세요~

**Comment by alex-koko** [comment]
확인했습니다!!
