### ISSUE TITLE
[BUG] Failed to execute 'createElement' on 'Document'

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#13]
## 🐛 Bug Issue

Failed to execute 'createElement' on 'Document': The qualified name provided ('static/media/src/assets/baby_mussuk.svg') contains the invalid character '/'.

## 🔍 To-do

- [x] storybook에서 svg 사용 할 수 있도록 설정하기

**Comment by ramrami-B** [comment]
## 💡 Solution
.storybook/main.js에 아래 코드 추가 (webpack 설정)

```js
webpackFinal: config => {
    const fileLoaderRule = config.module.rules.find(rule => rule.test && rule.test.test(".svg"));
    fileLoaderRule.exclude = /\.svg$/;

    config.module.rules.push({
      test: /\.svg$/,
      enforce: "pre",
      loader: require.resolve("@svgr/webpack"),
    });

    return config;
},
```

## 📚 Reference
https://stackoverflow.com/a/61706308/10331102

**Comment by ramrami-B** [comment]
faa36bb4b66c2c05e98ddcba47670f781448f872

bug 수정해서 develop 브랜치에 바로 push 했습니다~!
확인 후 이슈 닫아 주세요 :)

**Comment by alex-koko** [comment]
확인했습니다!
고생하셨어요!
