### ISSUE TITLE
[패키지 설치] redux 설치

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#28]
## 📍 Description

redux-toolkit 라이브러리 사용과 API 통신을 위한 패키지 설치

24f839988d410525d796d705a85f8b4e27991d36

## 🌟 To-do
`git pull origin develop` 이후 아래 명령어 실행

`npm install @reduxjs/toolkit`
`npm install react-redux`

**Comment by ramrami-B** [comment]
확인 후 이슈 닫아주세요 :)

**Comment by alex-koko** [comment]
확인했습니다!!
